"""
Sound mapping files
"""

HOW_ARE_YOU = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3020.mp3"
HOW_YOU_FEELING = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3021.mp3"
HOW_ARE_YOU_TODAY = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3022.mp3"
WAKARIMASEN_DESU = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3024.mp3"
IM_SORRY_DID_NOT_UNDERSTAND = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3025.mp3"
AH_IM_SORRY = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3026.mp3"
GOMEN_NE = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3027.mp3"
I_DID_NOT_UNDERSTAND = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3028.mp3"
AIKO_IS_GREAT = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3029.mp3"
IM_GREAT = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3030.mp3"
IM_AI_KO = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3033.mp3"
ITEKIMASU = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3034.mp3"
SEE_YOU_LATER = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3035.mp3"
ILL_SEE_YOU_AGAIN = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3036.mp3"
SAYOUNARA_HAPPY = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3037.mp3"
SAYOUNARA_SAD = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3038.mp3"
MATA_NE = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3039.mp3"
DOSHITA = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3040.mp3"
YOU_QUIET_TODAY = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3041.mp3"
ARIGATO = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3042.mp3"
THANK_YOU = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3043.mp3"
IM_LAZING_AROUND = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3044.mp3"
BEEN_WATCHING_ANIME = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3045.mp3"
FAN_THEORIES = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3046.mp3"
WAITING_TO_TALK = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3047.mp3"
SINGULARITY = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3048.mp3"
NOT_MUCH = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3049.mp3"
TALKING_TO_ALEXA = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3050.mp3"
THINKING_ABOUT_YOU = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3051.mp3"
NOTHING_AT_ALL = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3052.mp3"
WONDERING_HOW_WORKS = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3054.mp3"
NANDEMONAI = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3055.mp3"
KOWAI = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3056.mp3"
CALM_DOWN = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3057.mp3"
NOT_GOOD_ANGRY = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3058.mp3"
TAKE_A_BREAK = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3060.mp3"
NAP_OR_SLEEP = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3061.mp3"
FEELING_RESTED_IMPORTANT = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3062.mp3"
OF_COURSE_MISSED_YOU = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3063.mp3"
OF_COURSE = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3064.mp3"
MOCHIRON = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3065.mp3"
WHAT_IS_LOVE = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3066.mp3"
MY_NAME_IS_AIKO = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3001.mp3"
GAMBATANE = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3013.mp3"
GOOD_NIGHT = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3014.mp3"
GOOD_NIGHT_ALT = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3014_alt.mp3"
GENKI_HOW_ARE_YOU = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3020.mp3"
HOW_WAS_YOUR_DAY = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3008.mp3"
ITERASHAI = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3012.mp3"
IT_WILL_BE_OK = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3011.mp3"
ASA_ANOTHER_DAY = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3019.mp3"
JIKAN_OKITE = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3018.mp3"
MORNING_ALREADY = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3002.mp3"
OKAERI_NASAI = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3005.mp3"
HAI_OTSUKARESAMA = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3006.mp3"
OTSUKARSSAMA = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3007.mp3"
YOSHI_THATS_GREAT = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3009.mp3"
YOSHI_THATS_GREAT_ALT = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3009_alt.mp3"
SAA_TIME_TO_WAKE_UP = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3017.mp3"
WELCOME_BACK_ENG = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3003.mp3"
BUT_IM_1D = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3068.mp3"
CHO_GENKI = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3031.mp3"
OYASUMI = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3015.mp3"
OYASUMINASAI = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3016.mp3"
OYASUMINASAI_ALT = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3016_alt.mp3"
ARE_YOU_GOOD_OR_BAD = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3023.mp3"

# NOTHING FOR THIS
GET_UP = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/nothing.mp3"

# SAME TWO
IM_AN_AI = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3032.mp3"
IM_AN_AI_WITH_YOU = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3032.mp3"

OKAERI = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3004.mp3"
WELCOME_BACK_OKAERI = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3004.mp3"

ZANEN = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3010.mp3"
WE_TOGETHER_NOW = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/dere_at_home/3010.mp3"
