"""
ISP sound mappings
"""

WHAT_CAN_BE_PURCHASED_TSUNDERE_MODE = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/isp_discussion/9000.mp3"
WHAT_BUY_TSUNDERE_MODE = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/isp_discussion/9002.mp3"
WHAT_BUY_CAFE_DATE = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/isp_discussion/9003.mp3"
WHAT_BUY_TSUNDERE_AND_DATE = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/isp_discussion/9004.mp3"
UPSELL_1 = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/isp_discussion/9005.mp3"
UPSELL_2 = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/isp_discussion/9006.mp3"
DATE_DESCRIPTION = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/isp_discussion/9007.mp3"
TSUNDERE_DESCRIPTION = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/isp_discussion/9008.mp3"
FREE_VS_PAID = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/isp_discussion/9009.mp3"
DATE_PURCHASED = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/isp_discussion/9010.mp3"
DATE_PURCHASED_ALT = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/isp_discussion/9010_alt.mp3"
TSUNDERE_NOT_PURCHASED = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/isp_discussion/9011.mp3"
DATE_NOT_PURCHASED = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/isp_discussion/9012.mp3"
WELCOME_BACK_1 = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/isp_discussion/9013.mp3"
WELCOME_BACK_2 = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/isp_discussion/9013_alt_1.mp3"
WELCOME_BACK_3 = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/isp_discussion/9013_alt_2.mp3"
WELCOME_BACK_4 = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/isp_discussion/9013_alt_3.mp3"
WELCOME_BACK_5 = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/isp_discussion/9013_alt_4.mp3"
ALREADY_PURCHASED_TSUNDERE = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/isp_discussion/9014.mp3"
ALREADY_PURCHASED_DATE = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/isp_discussion/9015.mp3"
ASK_FOR_REFUND_TSUNDERE = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/isp_discussion/9016.mp3"
ASK_FOR_REFUND_DATE = "https://s3-us-west-2.amazonaws.com/crossfade-alexa-aiko-assets/isp_discussion/9017.mp3"
